apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: jenkins-ingress

---

apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: jenkins-home

---

apiVersion: v1

kind: Service

metadata:

  name: jenkins

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: jenkins